logging:
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    '[vn.com.unit.miragesql.miragesql]': ${LOGGING_LEVEL_SQL:DEBUG}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: ${DB_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
    url: jdbc:sqlserver://localhost:1433;databaseName=BOXCHAT_SOCKET;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    hikari:
      poolName: ${DB_POOL_NAME:${spring.application.name}}
      auto-commit: true
      register-mbeans: true
      idle-timeout: 600000
      minimum-idle: ${DB_CONN_MINIDLE:10}
      maximum-pool-size: ${DB_CONN_MAXACTIVE:100}
      connection-timeout: 30000
      max-lifetime: 1800000

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.SQLServerDialect


server:
  port: 8080
  servlet:
    context-path: /api/socket

jwt:
  signerKey: "bkPzUp7ltD/DRwHIyWdcscDb883yruLs2E9p5UpQRtmLaysoUoTDIOe1euDd93kQ"



