CREATE DATABASE BOXCHAT_SOCKET;
USE BOXCHAT_SOCKET;

CREATE TABLE PK_DEV_ACCOUNT(
	[USERNAME] [NVARCHAR](50) NOT NULL,
	[PASSWORD] [NVARCHAR](50) NOT NULL,
	[FULL_NAME] [NVARCHAR](50),
	[EMAIL] [NVARCHAR](50),
	[PHONE] [VARCHAR](15),
	[IMAGE] [VARCHAR](255),
	[ACTIVE] [FLOAT](1),
	[LDAP_FLAG] [FLOAT](1),
	[CREATED_BY] [NVARCHAR](50),
	[CREATED_DATE] [DATE],
	[UPDATED_BY] [NVARCHAR](50),
	[UPDATED_DATE] [DATE],
	[DELETED_BY] [NVARCHAR](50),
	[DELETED_DATE] [DATE],
 CONSTRAINT [PK_ACCOUNTS] PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO